Revert "Added make file for cache warming installation."
I think there's a missing dependency in buildroot:
  ImportError: No module named dns.resolver
  make[5]: *** [cache_warming.test] Error 1

This reverts commit f41fcfd0160c38fb63153a2e74cd13cf18f43af2.

Change-Id: I7c0e3e0402842659ffcb605557350ec6bcb46178