Revert "Updated Speedtest CLI for latest Speedtest server changes"
host-google_platform build fails:
config.cc:21:31: fatal error: jsoncpp/json/json.h: No such file or directory


This reverts commit 78e5f726adaa7a8f71ebceb3b96a1abade5fdfc0.

Change-Id: Ib3842b2d0a535e5f4335b58f1b0ab9a9f078eaec