platform: gcc 5.3 fix
build errors without this fix:

buildroot+google_platform.google_platform-HEAD: /usr/local/google/home/dpadgett/gfiber/out_gftv100/host/usr/bin/mipsel-linux-g++ -c -Wall -Werror -Wno-unused-local-typedefs -fPIC -Os -DPOSIX -DLINUX -D_DEBUG -DLOGGING=1 time.cc -o time.o
buildroot+google_platform.google_platform-HEAD: time.cc:68:15: error: ‘bruno_base::ignore’ defined but not used [-Werror=unused-variable]
buildroot+google_platform.google_platform-HEAD:  static uint32 ignore = StartTime();
buildroot+google_platform.google_platform-HEAD:                ^
buildroot+google_platform.google_platform-HEAD: cc1plus: all warnings being treated as errors
buildroot+google_platform.google_platform-HEAD: make[3]: *** [time.o] Error 1
buildroot+google_platform.google_platform-HEAD: make[3]: *** Waiting for unfinished jobs....
buildroot+google_platform.google_platform-HEAD: utils.cc: In function ‘bool speedtest::ParseInt(const string&, int*)’:
buildroot+google_platform.google_platform-HEAD: utils.cc:70:16: error: cannot convert ‘std::basic_istream<char>::__istream_type {aka std::basic_istream<char>}’ to ‘bool’ in return
buildroot+google_platform.google_platform-HEAD:    return n >> *result;
buildroot+google_platform.google_platform-HEAD:                 ^
buildroot+google_platform.google_platform-HEAD: make[3]: *** [utils.o] Error 1
buildroot+google_platform.google_platform-HEAD: make[2]: *** [speedtest/all] Error 2

Change-Id: I333c8efa819bfb06ade4529cd7b132608c924c45